### ISSUE TITLE
Web app for ILC config - True booleans versus true

### ISSUE THREAD

**Issue by bbartling** [VOLTTRON/volttron-pnnl-applications#39]
When I made the ILC config file with the web app, I notice that the Boolean data comes through as `true` not `True`. Is that because the web app is maybe JavaScript and the VOLTTRON is Python where `true` is throwing an error on my end.

{"config":
           {"type":"json","data":
            {"campus":"slipstream_internal","building":"slipstream_hq","power_meter":
             {"device_topic":"  slipstream_internal/slipstream_hq/5232",
              "device_name":"5232","point":"REGVAL total_rtu_power",
              "demand_formula":{"operation":"REGVAL total_rtu_power / 1000",
                                "operation_args":["REGVAL total_rtu_power"]}},
             "agent_id":"Cal",
             "demand_limit":"10",
             "control_time":5,
             "curtailment_break":9,
             "average_building_power_window":10,
             "stagger_release":**_true_**,
             "stagger_off_time":**_true_**,

**Comment by craig8** [comment]
this is json data.  json doesn't have a True operator which is why you got the error.  true is the syntax available for json, which is obviously the conclusion you got to.
